### ISSUE TITLE
Fix bug with adding functions

### ISSUE THREAD

**Issue by nvnikolov** [datagraft/grafterizer-2.0#14]
Adding functions sometimes results in empty objects in the pipeline of the transformation object

**Comment by nvnikolov** [comment]
Could be a race condition between the pipeline events service subjects updates (the pipeline event subject gets updated before the currently selected function subject)

**Comment by bmzernichow** [comment]
Suggest that we close this issue. Bug has not occured lately. Will reopen issue if we find that empty objects are still added to pipeline.
