### ISSUE TITLE
Support for new transformation

### ISSUE THREAD

**Issue by nvnikolov** [datagraft/grafterizer-2.0#22]
Add support for creating new transformations from scratch.

- [x] Route for new transformation without a publisher ID (anonymous) - needed for the first load of the application
- [x] Re-route on save to URL with the newly created transformation ID
- [x] Save (create new transformation) and re-route to URL on file upload by user

**Comment by bmzernichow** [comment]
Implemented in commit 8c4329c8ca95f39650a51e151564e2dad3c2fc4e

**Comment by nvnikolov** [comment]
The path /transformations/new/tabular-transformation does not work. Should be the default path when accessing the UI and start the OAuth flow to determine the user name

**Comment by bmzernichow** [comment]
Implemented in commit a42f69f63ceb83954411c63e34e16f08240628ff
