### ISSUE TITLE
Implement read-only view

### ISSUE THREAD

**Issue by nvnikolov** [datagraft/grafterizer-2.0#28]
Implement read-only view for a transformation whose owner is different from the logged in user
- [x] Disable edit steps of transformation (incl. removing the sidebar)
- [x] Disable edit of metadata
- [x] Disable edit RDF mappings and Tabular Annotations
- [x] Enable file preview

**Comment by bmzernichow** [comment]
Implemented in commit d446466c679ac365778e3c082076b80f93738880
