### ISSUE TITLE
Implement transformation-only view

### ISSUE THREAD

**Issue by nvnikolov** [datagraft/grafterizer-2.0#29]
Implement a view that supports preview of transformations without a file loaded in the UI. Related to #28.

- [x] Remove table view
- [x] Provide suggestions for all possible functions to add when editing
- [x] Remove profiling
- [x] Remove Tabular Annotation view

**Comment by bmzernichow** [comment]
Implemented in commit 5907cc686769cf4e04bad62f2162ac457e1d0933
