### ISSUE TITLE
Beginning OAuth flow causes errors

### ISSUE THREAD

**Issue by nvnikolov** [datagraft/grafterizer-2.0#31]
Both transformation and dispatch services resolve with message "Beginning OAuth flow" whenever the UI has not obtained credentials. This causes errors in some cases, e.g.,:

- [x] Downloading result of transformation
- [x] Initialising transformation object

This needs to be handled better

**Comment by bmzernichow** [comment]
Fixed in commits 71ba370d9161ce0b645440037c33bfb7963ed288 and a42f69f63ceb83954411c63e34e16f08240628ff
