### ISSUE TITLE
Once a row/column is selected, the list of functions cannot be reset

### ISSUE THREAD

**Issue by nvnikolov** [datagraft/grafterizer-2.0#48]
In the tabular view, once the user selects a column or row, the suggested transformation functions cannot be reset to the defaults even if the selection is cleared. There is no obvious option to clear selection, although if the user clicks outside the table, it is cleared.

- [ ] Reset suggested transformation functions on selection
- [ ] Make an obvious option to clear selection (e.g., a button "Clear selection") 
- [ ] (if possible) Clear selection when the user clicks a second time on the selected column/row

**Comment by bmzernichow** [comment]
Fixed in c06caf35cdd569abcdbc8514accda11133444a4b
