### ISSUE TITLE
Content is not saved when switching between tabs in UI

### ISSUE THREAD

**Issue by bmzernichow** [datagraft/grafterizer-2.0#61]
Refactor save function in app component by moving code to transformation service. Trigger save() in all three components (tabular/ rdf/ annotation) when components are destroyed (ngOnDestroy()), I.e., when clicking a new tab.

**Comment by bmzernichow** [comment]
Working on this now - have tested that suggested fix works.

**Comment by nvnikolov** [comment]
definitely do NOT do that

**Comment by nvnikolov** [comment]
Fixed in 733f33e7e7d95ef4bf478a9ce18343574876274e
