### ISSUE TITLE
Missing pipeline functions

### ISSUE THREAD

**Issue by nvnikolov** [datagraft/grafterizer-2.0#66]
- [x] Group and aggregate
- [x] Rename column
- [x] Add row
- [x] Filter rows
- [x] Custom function

**Comment by bmzernichow** [comment]
Implemented in commits a49ec6b81f2f5f6b9b00d840da788a801b19e986 69d06c5a481559782098a6489b2a8fe6a4951fd8 30ff729553f35935916af67c110bd736debcf44c f968cdcb451a81db82f894ccecc50942f0e787f2 a8288a5ed70a89a955d302043c8b5d8f57143b43 9cd421adf8447c6c1b92eb46f409fae2bbab4efe
