### ISSUE TITLE
Duplicate generation of RDF data

### ISSUE THREAD

**Issue by bmzernichow** [datagraft/grafterizer-2.0#82]
Context to replicate problem: Production version of grafterizer, public transformation 'feiii-challenge-california-companies', public dataset 'CA-corporate-registrations-sample'

Problem: duplicate entries of triples are generated when choosing to download triples or RDF JAR. Issue seems to be related to existense of two identical graphs which are not visible in UI.

**Comment by nvnikolov** [comment]
Fixed in 3d6f5bc0e49d6fc12ea2300e256f9cf92db31f7c
