### ISSUE TITLE
Tabular annotation mapping produces only one tuple

### ISSUE THREAD

**Issue by vcutrona** [datagraft/grafterizer-2.0#87]
Only one triple is generated when downloading the .nt triples using the tabular mapping.
How to reproduce:

1. Copy the [ewsc-tutorial-dataset](https://datagraft.io/nvnikolov/filestores/eswc-tutorial-dataset) file
2. Create a new transformation
3. Upload the previously copied file
4. Add the _Make dataset_ step to the transformation pipeline, selecting the _First row as header_ option
5. Switch to the Tabular Enrichment tab
6. Reconcile the **StrCity** column against the GeoNames service (_geo group_) and create a new column (**StrCity_geon**)
7. Annotate the **StrCity** column as Literal (string) and link it to the **StrCity_geon** column via the _http://www.w3.org/2000/01/rdf-schema#label_ property.
8. Save the pipeline and click the _Update RDF mappings_ button
9. Switch to the RDF mapping tab and select the Tabular annotation mappings tab in the left panel
10. Check that a new root node is there, linked to two object nodes
11. Click on the download button and select _Download result as RDF_ (use the N-Triples default format)

**RESULT**: The downloaded file contains only one row, instead of 1362 (2 triples per row expected).

**Comment by nvnikolov** [comment]
Fixed in 2e8bf4890343ae342328fb58b01dbdedfffea770
