### ISSUE TITLE
Wikidata Reconciliation service is not working

### ISSUE THREAD

**Issue by vcutrona** [datagraft/grafterizer-2.0#88]
The Wikidata Reconciliation service does not work. The actual in-use version has been labeled as "old" by the maintainers, while a new version of the service is available at https://wdreconcile.toolforge.org/.

How to reproduce:

1. Copy the [ewsc-tutorial-dataset](https://datagraft.io/nvnikolov/filestores/eswc-tutorial-dataset) file
2. Create a new transformation
3. Upload the previously copied file
4. Add the _Make dataset_ step to the transformation pipeline, selecting the _First row as header_ option
5. Switch to the Tabular Enrichment tab
6. Reconcile the **StrCity** column against the Wikidata (old) Reconciliation service (_general group_)

**RESULT**: the app is stuck while loading and the _502 bad gateway_ error is displayed.

**Comment by nvnikolov** [comment]
This is not a bug in Grafterizer. It seems to be a hard-coded configuration in the production version of the ASIA service "conciliator". Please post bugs/issues in the respective repositories.

**Comment by vcutrona** [comment]
The error should be handled also in the frontend, otherwise, the application is stuck while loading (a refresh is needed).
