### ISSUE TITLE
CloudFront error when reconciling with Wikifier 

### ISSUE THREAD

**Issue by vcutrona** [datagraft/grafterizer-2.0#89]
Sometimes the Wikifier for Tables Reconciliation service does not work.

How to reproduce:*

1. Copy the [ewsc-tutorial-dataset](https://datagraft.io/nvnikolov/filestores/eswc-tutorial-dataset) file
2. Create a new transformation
3. Upload the previously copied file
4. Add the _Make dataset_ step to the transformation pipeline, selecting the _First row as header_ option
5. Switch to the Tabular Enrichment tab
6. Reconcile the **StrCity** column against the Wikifier for Tables Reconciliation service (_general group_)

**RESULT**: the app is stuck while loading and the server responded with a status 504 (CloudFront - The request could not be satisfied).

\* If it works, try to annotate other columns (e.g., **Keyword**) in the same session, against the same service, until the exception is thrown.

**Comment by nvnikolov** [comment]
504 is not an error code - this is a gateway timeout. Most likely it is thrown because the back-end service hangs for more than 30 seconds (this is the maximum amount that CloudFront waits to serve results of back-end processing). Not an issue of Grafterizer
