### ISSUE TITLE
Default URIfy prefix is missing on automatically generated URI column annotations

### ISSUE THREAD

**Issue by vcutrona** [datagraft/grafterizer-2.0#90]
When set, the default URIfy prefix is not loaded on automatically generated URI source columns

How to reproduce:

1. Create a new transformation and upload a file
2. Switch to the Tabular Enrichment tab
3. Open the config panel (gear icon) and set a default URIfy prefix (e.g., http://my.example/rdf#)
4. Annotate a column (**A**) as a literal column of type string, and set as its source column a non-annotated column (**B**).

**RESULT**: The default URIfy prefix is missing when editing the annotation of **B**.

**Comment by nvnikolov** [comment]
Fixed in b6d6107f2903f92f7810ac4d85a605932392a5ad
